import {
  Article,
  Category,
  EPaperEdition,
  User,
  LocationNode,
  EditorialAssignment,
  SocialPost,
  CitizenReport,
  LiveStreamData,
  AdCampaign,
  VideoItem,
  PhotoAlbum,
  PushAlert,
} from "./types";

export const demoUsers: User[] = [
  {
    id: "usr-super-admin",
    name: "राजेश वर्मा (Rajesh Verma)",
    email: "superadmin@groundzero.media",
    role: "SUPER_ADMIN",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
    district: "हरियाणा (HQ)",
    phone: "+91 98765 43210",
    bio: "Chief Executive & Platform Administrator",
  },
  {
    id: "usr-editor-in-chief",
    name: "अमित कुमार (Amit Kumar)",
    email: "editor@groundzero.media",
    role: "EDITOR_IN_CHIEF",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    district: "हरियाणा",
    phone: "+91 98123 45678",
    bio: "Editor-in-Chief & Fact Checking Lead",
  },
  {
    id: "usr-district-editor",
    name: "सतीश यादव (Satish Yadav)",
    email: "satish.editor@groundzero.media",
    role: "DISTRICT_EDITOR",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    district: "महेंद्रगढ़ / Mahendergarh",
    phone: "+91 94160 12345",
    bio: "District Bureau Chief, South Haryana",
  },
  {
    id: "usr-reporter-narnaul",
    name: "नवीन शर्मा (Naveen Sharma)",
    email: "naveen.reporter@groundzero.media",
    role: "REPORTER",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    district: "नारनौल / Narnaul",
    phone: "+91 99912 34567",
    bio: "Field Senior Reporter, Narnaul & Ateli",
  },
  {
    id: "usr-social-lead",
    name: "प्रिया राव (Priya Rao)",
    email: "social@groundzero.media",
    role: "SOCIAL_MEDIA_MANAGER",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    district: "डिजिटल डेस्क",
    phone: "+91 97280 88888",
    bio: "Social Media Command Center Lead",
  },
  {
    id: "usr-citizen",
    name: "विकास चौधरी (Vikas Choudhary)",
    email: "vikas.citizen@gmail.com",
    role: "CITIZEN_CONTRIBUTOR",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80",
    district: "रेवाड़ी / Rewari",
    phone: "+91 98960 99999",
    bio: "Community Journalist & Active Citizen",
  },
];

export const haryanaLocations: LocationNode[] = [
  { id: "loc-hr", name: "Haryana", nameHi: "हरियाणा", slug: "haryana", type: "state" },
  
  // South Haryana Districts
  { id: "loc-mgarh", name: "Mahendergarh", nameHi: "महेंद्रगढ़", slug: "mahendergarh", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 32 },
  { id: "loc-rewari", name: "Rewari", nameHi: "रेवाड़ी", slug: "rewari", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 28 },
  { id: "loc-ggn", name: "Gurugram", nameHi: "गुरुग्राम", slug: "gurugram", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 35 },
  { id: "loc-fbd", name: "Faridabad", nameHi: "फरीदाबाद", slug: "faridabad", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 26 },
  { id: "loc-nuh", name: "Nuh (Mewat)", nameHi: "नूह (मेवात)", slug: "nuh", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 20 },
  { id: "loc-palwal", name: "Palwal", nameHi: "पलवल", slug: "palwal", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 18 },
  { id: "loc-dadri", name: "Charkhi Dadri", nameHi: "चरखी दादरी", slug: "charkhi-dadri", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 15 },
  { id: "loc-jhajjar", name: "Jhajjar", nameHi: "झज्जर", slug: "jhajjar", type: "district", parentId: "loc-hr", state: "Haryana", newsCount: 17 },
  
  // Tehsils / Cities / Towns
  { id: "loc-narnaul", name: "Narnaul", nameHi: "नारनौल", slug: "narnaul", type: "city", parentId: "loc-mgarh", district: "Mahendergarh", state: "Haryana", newsCount: 22 },
  { id: "loc-ateli", name: "Ateli", nameHi: "अटेली", slug: "ateli", type: "tehsil", parentId: "loc-mgarh", district: "Mahendergarh", state: "Haryana", newsCount: 11 },
  { id: "loc-kanina", name: "Kanina", nameHi: "कनीना", slug: "kanina", type: "tehsil", parentId: "loc-mgarh", district: "Mahendergarh", state: "Haryana", newsCount: 9 },
  { id: "loc-rewari-city", name: "Rewari City", nameHi: "रेवाड़ी शहर", slug: "rewari-city", type: "city", parentId: "loc-rewari", district: "Rewari", state: "Haryana", newsCount: 18 },
  { id: "loc-bawal", name: "Bawal", nameHi: "बावल", slug: "bawal", type: "tehsil", parentId: "loc-rewari", district: "Rewari", state: "Haryana", newsCount: 14 },
  { id: "loc-dharuhera", name: "Dharuhera", nameHi: "धारूहेड़ा", slug: "dharuhera", type: "city", parentId: "loc-rewari", district: "Rewari", state: "Haryana", newsCount: 12 },
  { id: "loc-kosli", name: "Kosli", nameHi: "कोसली", slug: "kosli", type: "tehsil", parentId: "loc-rewari", district: "Rewari", state: "Haryana", newsCount: 10 },
  { id: "loc-manesar", name: "Manesar", nameHi: "मानेसर", slug: "manesar", type: "city", parentId: "loc-ggn", district: "Gurugram", state: "Haryana", newsCount: 16 },
  { id: "loc-sohna", name: "Sohna", nameHi: "सोहना", slug: "sohna", type: "tehsil", parentId: "loc-ggn", district: "Gurugram", state: "Haryana", newsCount: 13 },
  { id: "loc-pataudi", name: "Pataudi", nameHi: "पटौदी", slug: "pataudi", type: "tehsil", parentId: "loc-ggn", district: "Gurugram", state: "Haryana", newsCount: 11 },
  { id: "loc-ballabhgarh", name: "Ballabhgarh", nameHi: "बल्लभगढ़", slug: "ballabhgarh", type: "city", parentId: "loc-fbd", district: "Faridabad", state: "Haryana", newsCount: 15 },
  { id: "loc-tauru", name: "Tauru", nameHi: "तावडू", slug: "tauru", type: "tehsil", parentId: "loc-nuh", district: "Nuh (Mewat)", state: "Haryana", newsCount: 9 },
  { id: "loc-punhana", name: "Punhana", nameHi: "पुन्हाना", slug: "punhana", type: "tehsil", parentId: "loc-nuh", district: "Nuh (Mewat)", state: "Haryana", newsCount: 8 },
  { id: "loc-hodal", name: "Hodal", nameHi: "होडल", slug: "hodal", type: "tehsil", parentId: "loc-palwal", district: "Palwal", state: "Haryana", newsCount: 8 },
  { id: "loc-hathin", name: "Hathin", nameHi: "हथीन", slug: "hathin", type: "tehsil", parentId: "loc-palwal", district: "Palwal", state: "Haryana", newsCount: 7 },
  { id: "loc-bahadurgarh", name: "Bahadurgarh", nameHi: "बहादुरगढ़", slug: "bahadurgarh", type: "city", parentId: "loc-jhajjar", district: "Jhajjar", state: "Haryana", newsCount: 14 },
  { id: "loc-beri", name: "Beri", nameHi: "बेरी", slug: "beri", type: "tehsil", parentId: "loc-jhajjar", district: "Jhajjar", state: "Haryana", newsCount: 8 },
  { id: "loc-badhra", name: "Badhra", nameHi: "बाढड़ा", slug: "badhra", type: "tehsil", parentId: "loc-dadri", district: "Charkhi Dadri", state: "Haryana", newsCount: 9 },
];

export const initialCategories: Category[] = [
  {
    "id": "top",
    "name": "ताज़ा खबरें",
    "slug": "top"
  },
  {
    "id": "mahendergarh",
    "name": "महेंद्रगढ़ / नारनौल",
    "slug": "mahendergarh"
  },
  {
    "id": "rewari",
    "name": "रेवाड़ी / बावल",
    "slug": "rewari"
  },
  {
    "id": "gurugram",
    "name": "गुरुग्राम / मानेसर",
    "slug": "gurugram"
  },
  {
    "id": "faridabad",
    "name": "फरीदाबाद / बल्लभगढ़",
    "slug": "faridabad"
  },
  {
    "id": "nuh",
    "name": "नूह (मेवात)",
    "slug": "nuh"
  },
  {
    "id": "palwal",
    "name": "पलवल / होडल",
    "slug": "palwal"
  },
  {
    "id": "mandi-bhav",
    "name": "कृषि व मंडी भाव",
    "slug": "mandi-bhav"
  },
  {
    "id": "ahirwal",
    "name": "अहीरवाल हलचल",
    "slug": "ahirwal"
  },
  {
    "id": "south-haryana",
    "name": "साउथ हरियाणा विशेष",
    "slug": "south-haryana"
  }
];

export const initialArticles: Article[] = [
  {
    "id": "rewari-dharuhera-gurugram-expressway",
    "title": "Rewari News | रेवाड़ी-धारूहेड़ा-गुरुग्राम नए एलिवेटेड कॉरिडोर को केंद्र की मंजूरी : ₹3,200 करोड़ की लागत | जाम से मिलेगी मुक्ति, उद्योग को लगेंगे पंख",
    "slug": "rewari-dharuhera-gurugram-elevated-corridor-approved",
    "excerpt": "रेवाड़ी से धारूहेड़ा और मानेसर-गुरुग्राम के बीच नए एलिवेटेड हाईवे और 6-लेन चौड़ीकरण प्रोजेक्ट को केंद्रीय सड़क परिवहन मंत्रालय ने हरी झंडी दे दी है।",
    "content": "रेवाड़ी (ग्राउंड ज़ीरो ब्यूरो): दक्षिण हरियाणा के औद्योगिक और आर्थिक विकास को नई ऊंचाई देने के लिए केंद्रीय सड़क परिवहन मंत्रालय ने रेवाड़ी-धारूहेड़ा-गुरुग्राम 6-लेन एलिवेटेड कॉरिडोर परियोजना को अंतिम प्रशासनिक एवं वित्तीय मंजूरी दे दी है। इस महात्वाकांक्षी परियोजना पर कुल 3,200 करोड़ रुपये की लागत आएगी।\n\nसाउथ हरियाणा के लाखों दैनिक यात्रियों, वाहन चालकों और औद्योगिक कामगारों को रोजाना धारूहेड़ा चुंगी, बावल मोड़ और कापड़ीवास बॉर्डर पर घंटों लगने वाले भीषण जाम से पूरी तरह मुक्ति मिल जाएगी।\n\nपरियोजना के तहत रेवाड़ी बाईपास से धारूहेड़ा होते हुए मानेसर आईएमटी तक 42 किलोमीटर लंबे हिस्से में 4 मुख्य एलिवेटेड फ्लाईओवर्स और 8 अंडरपास का निर्माण किया जाएगा। लोक निर्माण विभाग (PWD) के अधिकारियों ने बताया कि अगले महीने से भूमि सर्वेक्षण और टेंडर प्रक्रिया शुरू कर दी जाएगी।\n\nक्षेत्रीय उद्योग संघों और व्यापारी संगठनों ने इस निर्णय का गर्मजोशी से स्वागत करते हुए कहा कि ग्राउंड ज़ीरो न्यूज़ द्वारा लगातार उठाए गए इस जनमुद्दे का ही परिणाम है कि आज शासन-प्रशासन हरकत में आया है।",
    "category": "रेवाड़ी / बावल",
    "categorySlug": "rewari",
    "imageUrl": "https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "रेवाड़ी-गुरुग्राम राष्ट्रीय राजमार्ग पर प्रस्तावित नए एलिवेटेड कॉरिडोर का रेखाचित्र",
    "youtubeId": "dewccxNzJbU",
    "isBreaking": true,
    "isLeadStory": true,
    "views": 8420,
    "author": "राजेश यादव, वरिष्ठ संवाददाता, रेवाड़ी",
    "reporterName": "राजेश यादव",
    "district": "Rewari",
    "city": "Rewari",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-24T04:30:00.000Z",
    "publishedAt": "2026-09-24T04:30:00.000Z",
    "tags": [
      "रेवाड़ी",
      "धारूहेड़ा",
      "गुरुग्राम",
      "हाईवे",
      "साउथ हरियाणा",
      "बावल"
    ]
  },
  {
    "id": "narnaul-medical-college-trauma-center",
    "title": "Narnaul News | नारनौल मेडिकल कॉलेज में 100 नए डॉक्टरों की तैनाती व एडवांस ट्रॉमा सेंटर शुरू : डीसी ने किया निरीक्षण | 24 घंटे आईसीयू व डायलिसिस सेवा उपलब्ध",
    "slug": "narnaul-medical-college-trauma-center-expansion",
    "excerpt": "दक्षिण हरियाणा के सबसे बड़े चिकित्सा केंद्र नारनौल मेडिकल कॉलेज में स्वास्थ्य सेवाओं का विस्तार करते हुए 100 नए डॉक्टरों और आधुनिक डायलिसिस यूनिट का शुभारंभ किया गया।",
    "content": "नारनौल (ग्राउंड ज़ीरो ब्यूरो): दक्षिण हरियाणा और अहीरवाल अंचल के मरीजों को विश्वस्तरीय स्वास्थ्य सेवाएं उपलब्ध कराने के लिए नारनौल राजकीय मेडिकल कॉलेज एवं नागरिक अस्पताल परिसर में 100 नए विशेषज्ञ डॉक्टरों और 180 नर्सिंग अधिकारियों की विधिवत तैनाती कर दी गई है।\n\nजिला उपायुक्त (DC) ने आज अस्पताल का औचक निरीक्षण कर नवनिर्मित 24x7 एडवांस ट्रॉमा सेंटर, न्यूरो सर्जरी विंग और 20 बेड की आधुनिक डायलिसिस यूनिट का जायजा लिया। उपायुक्त ने स्पष्ट निर्देश दिए कि किसी भी आपातकालीन स्थिति में मरीज को जयपुर या दिल्ली रेफर करने की नौबत न आए, सभी जीवनरक्षक दवाइयां और ऑक्सीजन की निर्बाध आपूर्ति अस्पताल में 24 घंटे सुनिश्चित की जाए।\n\nमहेंद्रगढ़ जिले के अटेली, कनीना, नांगल चौधरी और सतनाली क्षेत्र के ग्रामीणों के लिए विशेष एम्बुलेंस हेल्पलाइन भी शुरू की गई है। सिविल सर्जन ने बताया कि ओपीडी में डिजिटल पर्ची काउंटर और निःशुल्क जांच लैब भी आज से पूरी क्षमता के साथ कार्य कर रहे हैं।",
    "category": "महेंद्रगढ़ / नारनौल",
    "categorySlug": "mahendergarh",
    "imageUrl": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "नारनौल मेडिकल कॉलेज के नवनिर्मित अत्याधुनिक आईसीयू व ट्रॉमा ब्लॉक का दृश्य",
    "youtubeId": "HoPzB9EpQfo",
    "isBreaking": true,
    "isLeadStory": true,
    "views": 6390,
    "author": "नवीन शर्मा, ब्यूरो चीफ, नारनौल",
    "reporterName": "नवीन शर्मा",
    "district": "Mahendergarh",
    "city": "Narnaul",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-24T03:45:00.000Z",
    "publishedAt": "2026-09-24T03:45:00.000Z",
    "tags": [
      "नारनौल",
      "महेंद्रगढ़",
      "स्वास्थ्य",
      "मेडिकल कॉलेज",
      "साउथ हरियाणा"
    ]
  },
  {
    "id": "ahirwal-aarti-rao-development-blueprint",
    "title": "Ahirwal News | आरती राव बोलीं- साउथ हरियाणा की तरक्की और टेल तक नहरी पानी पहुंचाना हमारा मुख्य संकल्प : अहीरवाल की चौपालों में जनसंवाद तेज",
    "slug": "ahirwal-aarti-rao-south-haryana-canal-water-commitment",
    "excerpt": "रेवाड़ी और महेंद्रगढ़ के दौरे पर पहुंचीं आरती राव ने कहा कि दक्षिण हरियाणा के शुष्क क्षेत्रों में नहरी पानी पहुंचाना और युवाओं के लिए औद्योगिक रोजगार के नए अवसर हमारी सर्वोच्च प्राथमिकता है।",
    "content": "रेवाड़ी/नारनौल: अहीरवाल के ऐतिहासिक गांवों में आयोजित विशाल जनसंवाद यात्रा के दौरान वरिष्ठ नेत्री आरती राव का पगड़ी और शॉल ओढ़ाकर भव्य नागरिक अभिनंदन किया गया। जनसभा को संबोधित करते हुए उन्होंने कहा कि साउथ हरियाणा स्वाभिमान, देशभक्ति और कर्मठता की पावन धरा है और यहां के युवाओं के हक के लिए वे निरंतर संघर्षरत रहेंगी।\n\nउन्होंने कहा कि महेंद्रगढ़ और रेवाड़ी जिले की दक्षिणी सीमाओं तक जवाहरलाल नेहरू कनाल फीडर के जरिए नहरी पानी पहुंचाने का काम युद्ध स्तर पर चल रहा है। बावल और धारूहेड़ा के औद्योगिक क्लस्टर्स में स्थानीय युवाओं को 75% रोजगार सुनिश्चित कराने के लिए कौशल विकास केंद्रों (Skill Hubs) की स्थापना की जाएगी।\n\nसैकड़ों गांवों से आए सरपंचों और पंचों ने मांग पत्र सौंपे, जिस पर आरती राव ने तुरंत संबंधित प्रशासनिक अधिकारियों को दूरभाष पर जनहितैषी समाधान के कड़े निर्देश दिए।",
    "category": "अहीरवाल हलचल",
    "categorySlug": "ahirwal",
    "imageUrl": "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "रेवाड़ी जिले के बूढ़पुर जनसंवाद में आरती राव का पगड़ी पहनाकर स्वागत करते बुजुर्ग व ग्रामीण",
    "youtubeId": "FDmAQEX54Gg",
    "isBreaking": true,
    "isLeadStory": true,
    "views": 9150,
    "author": "सुरेश कुमार, राजनीतिक विश्लेषक",
    "reporterName": "सुरेश कुमार",
    "district": "Rewari",
    "city": "Rewari",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-24T02:15:00.000Z",
    "publishedAt": "2026-09-24T02:15:00.000Z",
    "tags": [
      "आरती राव",
      "अहीरवाल",
      "रेवाड़ी",
      "महेंद्रगढ़",
      "राजनीति",
      "साउथ हरियाणा"
    ]
  },
  {
    "id": "south-haryana-mustard-procurement-bonus",
    "title": "Mandi Bhav | दक्षिण हरियाणा की मंडियों में सरसों की बंपर आवक : नारनौल, रेवाड़ी व अटेली में ₹5,780 तक पहुंचे भाव | भावांतर भरपाई का भुगतान शुरू",
    "slug": "south-haryana-mustard-bajra-mandi-bhav-procurement",
    "excerpt": "महेंद्रगढ़, रेवाड़ी और चरखी दादरी की अनाज मंडियों में नई सरसों और बाजरे की खरीद प्रक्रिया तेज। ई-नाम पोर्टल पर सीधे किसानों के खातों में भुगतान जारी।",
    "content": "नारनौल/रेवाड़ी: दक्षिण हरियाणा की प्रमुख कृषि उपज मंडियों में आज रबी सीजन की प्रमुख तिलहन फसल पीली व काली सरसों की आवक में भारी उछाल दर्ज किया गया। नारनौल नई अनाज मंडी में अच्छी गुणवत्ता वाली सरसों 5,780 रुपये प्रति क्विंटल तक बिकी, जो न्यूनतम समर्थन मूल्य (MSP) से भी ऊपर है।\n\nमंडी प्रशासन ने किसानों की सुविधा के लिए शेड, पेयजल और पारदर्शी इलेक्ट्रॉनिक तुलाई कांटे लगाए हैं। अटेली, कनीना, बावल और रेवाड़ी मंडी सचिवों ने बताया कि 'मेरी फसल मेरा ब्योरा' पोर्टल पर पंजीकृत किसानों को सीधे उनके बैंक खातों में डीबीटी के जरिए 48 से 72 घंटों के भीतर फसल भुगतान की गारंटी दी गई है।\n\nकृषि उप-निदेशक ने बताया कि बाजरे के किसानों को भी भावांतर भरपाई योजना के तहत 450 रुपये प्रति क्विंटल का बोनस सीधे हस्तांतरित किया जा रहा है।",
    "category": "कृषि व मंडी भाव",
    "categorySlug": "mandi-bhav",
    "imageUrl": "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "नारनौल नई अनाज मंडी में सरसों की ढेरियों की बोली लगाते आढ़ती व किसान",
    "youtubeId": "ScMzIvxBSi4",
    "isBreaking": false,
    "isLeadStory": false,
    "views": 5280,
    "author": "अमित यादव, कृषि संवाददाता",
    "reporterName": "अमित यादव",
    "district": "Mahendergarh",
    "city": "Narnaul",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-23T23:30:00.000Z",
    "publishedAt": "2026-09-23T23:30:00.000Z",
    "tags": [
      "मंडी भाव",
      "सरसों",
      "बाजरा",
      "नारनौल",
      "रेवाड़ी",
      "अटेली",
      "किसान"
    ]
  },
  {
    "id": "gurugram-manesar-msme-industrial-hub",
    "title": "Gurugram News | मानेसर-सोहना इंडस्ट्रियल बेल्ट में ₹5,000 करोड़ का नया निवेश : 25,000 स्थानीय युवाओं को मिलेंगे रोजगार के अवसर | ऑटोमोबाइल सेक्टर में बूम",
    "slug": "gurugram-manesar-industrial-hub-new-investment-jobs",
    "excerpt": "गुरुग्राम और मानेसर क्षेत्र में इलेक्ट्रॉनिक व ऑटोमोबाइल कंपनियों के नए प्लांट लगाने की योजना को स्वीकृति मिल गई है। सोहना रोड पर लॉजिस्टिक पार्क का होगा विस्तार।",
    "content": "गुरुग्राम (ग्राउंड ज़ीरो ब्यूरो): दक्षिण हरियाणा का औद्योगिक पावरहाउस मानेसर और सोहना अब देश का सबसे बड़ा एडवांस्ड मैन्युफैक्चरिंग हब बनने की ओर अग्रसर है। राज्य सरकार की औद्योगिक प्रोत्साहन नीति के तहत मानेसर आईएमटी फेज-2 और सोहना इंडस्ट्रियल कॉरिडोर में 28 नई कंपनियों ने 5,000 करोड़ रुपये से अधिक के निवेश समझौतों पर हस्ताक्षर किए हैं।\n\nइस नए निवेश से क्षेत्र के 25,000 से अधिक स्थानीय युवाओं को सीधे तकनीकी, लॉजिस्टिक्स और इंजीनियरिंग क्षेत्रों में सम्मानजनक रोजगार के नए अवसर मिलेंगे।\n\nउद्योग मंत्री ने बताया कि गुरुग्राम-पटौदी-रेवाड़ी एक्सप्रेसवे के दोनों किनारों पर विशेष एमएसएमई जोन विकसित किए जा रहे हैं, जहां प्लग-एंड-प्ले सुविधाएं उपलब्ध कराई जाएंगी। उद्योगों को 24 घंटे निर्बाध बिजली और हाई-स्पीड इंटरनेट कनेक्टिविटी देने के लिए समर्पित सबस्टेशन चालू किए गए हैं।",
    "category": "गुरुग्राम / मानेसर",
    "categorySlug": "gurugram",
    "imageUrl": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "मानेसर औद्योगिक क्षेत्र में संचालित आधुनिक मैन्युफैक्चरिंग एवं आईटी कॉरिडोर",
    "isBreaking": false,
    "isLeadStory": false,
    "views": 4820,
    "author": "संदीप भारद्वाज, गुरुग्राम",
    "reporterName": "संदीप भारद्वाज",
    "district": "Gurugram",
    "city": "Manesar",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-23T21:15:00.000Z",
    "publishedAt": "2026-09-23T21:15:00.000Z",
    "tags": [
      "गुरुग्राम",
      "मानेसर",
      "सोहना",
      "रोजगार",
      "उद्योग",
      "साउथ हरियाणा"
    ]
  },
  {
    "id": "faridabad-ballabhgarh-palwal-metro",
    "title": "Faridabad News | बल्लभगढ़ से पलवल तक मेट्रो विस्तार की डीपीआर को अंतिम मंजूरी : 24 किमी का नया रूट | 10 नए स्टेशन बनेंगे",
    "slug": "faridabad-ballabhgarh-palwal-metro-extension-approved",
    "excerpt": "फरीदाबाद-बल्लभगढ़-पलवल मेट्रो कॉरिडोर के निर्माण का मार्ग प्रशस्त हो गया है। इससे साउथ हरियाणा के लाखों दैनिक यात्रियों को तेज व सुगम सफर मिलेगा।",
    "content": "फरीदाबाद/पलवल: दक्षिण हरियाणा के दो बड़े औद्योगिक जिलों फरीदाबाद और पलवल को रैपिड मेट्रो कनेक्टिविटी से जोड़ने के ऐतिहासिक प्रोजेक्ट को हरियाणा मास रैपिड ट्रांसपोर्ट कॉरपोरेशन (HMRTC) ने हरी झंडी दे दी है।\n\nवर्तमान में बल्लभगढ़ के राजा नाहर सिंह मेट्रो स्टेशन तक चलने वाली वॉयलेट लाइन को 24 किलोमीटर आगे पलवल शहर तक विस्तारित किया जाएगा। इस रूट पर सीकरी, पृथला, बघौला, गदपुरी और पलवल बस स्टैंड सहित कुल 10 एलिवेटेड स्टेशन प्रस्तावित हैं।\n\nपृथला और बल्लभगढ़ औद्योगिक क्षेत्र के उद्यमियों ने कहा कि मेट्रो आने से दिल्ली, नोएडा और गुरुग्राम से कुशल कामगारों और इंजीनियरों का आवागमन बेहद सुगम हो जाएगा, जिससे दक्षिण हरियाणा का औद्योगिक उत्पादन दोगुना होगा। निर्माण कार्य आगामी वित्तीय वर्ष में शुरू होने का अनुमान है।",
    "category": "फरीदाबाद / बल्लभगढ़",
    "categorySlug": "faridabad",
    "imageUrl": "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "बल्लभगढ़-पलवल प्रस्तावित मेट्रो कॉरिडोर का आधुनिक ट्रेन मॉडल",
    "isBreaking": false,
    "isLeadStory": false,
    "views": 4190,
    "author": "मनोज तंवर, फरीदाबाद",
    "reporterName": "मनोज तंवर",
    "district": "Faridabad",
    "city": "Ballabhgarh",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-23T19:40:00.000Z",
    "publishedAt": "2026-09-23T19:40:00.000Z",
    "tags": [
      "फरीदाबाद",
      "बल्लभगढ़",
      "पलवल",
      "मेट्रो",
      "साउथ हरियाणा"
    ]
  },
  {
    "id": "nuh-mewat-drinking-water-project",
    "title": "Nuh News | मेवात क्षेत्र के 140 गांवों को मिलेगा शुद्ध नहरी पेयजल : ₹480 करोड़ की रेनीवेल परियोजना का कार्य 80% पूरा | तावडू व पुन्हाना में पाइपलाइन बिछी",
    "slug": "nuh-mewat-drinking-water-canal-pipeline-project",
    "excerpt": "नूह जिले में खारे पानी और जल संकट को हमेशा के लिए समाप्त करने के उद्देश्य से शुरू की गई रेनीवेल और नहरी जलापूर्ति योजना का कार्य अंतिम चरण में पहुंचा।",
    "content": "नूह (मेवात): दक्षिण हरियाणा के नूह जिले के सदियों पुराने खारे भूजल और पेयजल संकट का स्थायी समाधान अब साकार होने जा रहा है। जनस्वास्थ्य अभियांत्रिकी विभाग (Public Health) द्वारा 480 करोड़ रुपये की लागत से चलाई जा रही कोटला-रेनीवेल पेयजल परियोजना का 80 फीसदी कार्य सफलता पूर्वक पूरा कर लिया गया है।\n\nयमुना खादर क्षेत्र से शुद्ध मीठा पानी भूमिगत पाइपलाइनों के जरिए नूह, तावडू, पुन्हाना और फिरोजपुर झिरका के 140 दूरदराज के गांवों और ढाणियों तक पहुंचाया जा रहा है।\n\nउपायुक्त नूह ने बताया कि इस परियोजना के पूर्ण होते ही मेवात की 6 लाख से अधिक आबादी को प्रतिदिन प्रति व्यक्ति 70 लीटर स्वच्छ पेयजल उपलब्ध होगा। ग्रामीणों ने ग्राउंड ज़ीरो को बताया कि पहले महिलाओं को कई किलोमीटर दूर से पानी ढोना पड़ता था, अब घर-घर नल से जल आने से जीवन में बड़ा बदलाव आया है।",
    "category": "नूह (मेवात)",
    "categorySlug": "nuh",
    "imageUrl": "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "नूह के ग्रामीण क्षेत्र में बिछाई जा रही वृहद पेयजल फीडर पाइपलाइन",
    "isBreaking": false,
    "isLeadStory": false,
    "views": 3810,
    "author": "आरिफ खान, नूह मेवात",
    "reporterName": "आरिफ खान",
    "district": "Nuh (Mewat)",
    "city": "Nuh",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-23T17:10:00.000Z",
    "publishedAt": "2026-09-23T17:10:00.000Z",
    "tags": [
      "नूह",
      "मेवात",
      "तावडू",
      "पेयजल",
      "साउथ हरियाणा"
    ]
  },
  {
    "id": "palwal-kmp-expressway-logistics",
    "title": "Palwal News | केएमपी (KMP) और दिल्ली-मुंबई एक्सप्रेसवे इंटरचेंज के पास बनेगा साउथ हरियाणा का सबसे बड़ा एग्रो-लॉजिस्टिक पार्क",
    "slug": "palwal-kmp-expressway-agro-logistics-hub",
    "excerpt": "पलवल जिले में केएमपी और दिल्ली-मुंबई एक्सप्रेसवे के संगम पर आधुनिक वेयरहाउसिंग और कोल्ड स्टोरेज क्लस्टर स्थापित किया जाएगा।",
    "content": "पलवल/होडल: राष्ट्रीय राजधानी क्षेत्र और दक्षिण हरियाणा के प्रवेश द्वार पलवल में कुण्डली-मानेसर-पलवल (KMP) एक्सप्रेसवे और दिल्ली-वडोदरा-मुंबई सुपर एक्सप्रेसवे के जंक्शन पर 400 एकड़ भूमि पर एक अत्याधुनिक मल्टी-मॉडल लॉजिस्टिक्स और एग्रो-प्रोसेसिंग पार्क का निर्माण प्रस्तावित किया गया है।\n\nइस हब के बनने से पलवल, होडल, हथीन, फरीदाबाद और नूह के किसानों द्वारा उत्पादित सब्जियों, डेयरी उत्पादों और खाद्यान्नों को सीधे मुंबई, कांडला पोर्ट और दिल्ली की आजादपुर मंडी तक सुरक्षित व त्वरित रूप से भेजा जा सकेगा।\n\nपरियोजना में 50,000 मीट्रिक टन क्षमता के सौर ऊर्जा चालित कोल्ड स्टोरेज, पैकेजिंग यूनिट्स और किसान प्रशिक्षण केंद्र शामिल हैं। क्षेत्रीय विधायक और प्रशासनिक अधिकारियों ने संयुक्त रूप से स्थल का दौरा कर जमीन अधिग्रहण के मामलों को तेजी से निपटाने के निर्देश दिए हैं।",
    "category": "पलवल / होडल",
    "categorySlug": "palwal",
    "imageUrl": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "केएमपी एक्सप्रेसवे पलवल इंटरचेंज के समीप प्रस्तावित अत्याधुनिक लॉजिस्टिक हब",
    "isBreaking": false,
    "isLeadStory": false,
    "views": 3290,
    "author": "धर्मवीर शर्मा, पलवल",
    "reporterName": "धर्मवीर शर्मा",
    "district": "Palwal",
    "city": "Palwal",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-23T15:20:00.000Z",
    "publishedAt": "2026-09-23T15:20:00.000Z",
    "tags": [
      "पलवल",
      "होडल",
      "केएमपी",
      "एक्सप्रेसवे",
      "साउथ हरियाणा"
    ]
  },
  {
    "id": "ateli-kanina-rural-wrestling-talent",
    "title": "Mahendergarh News | अटेली और कनीना के अखाड़ों से निकले 6 पहलवानों का राष्ट्रीय टीम में चयन : साउथ हरियाणा के ग्रामीण खेल प्रतिभाओं का परचम",
    "slug": "ateli-kanina-rural-wrestling-national-selection",
    "excerpt": "कनीना और अटेली क्षेत्र के युवा पहलवानों ने नेशनल कुश्ती चैंपियनशिप में स्वर्ण व रजत पदक जीतकर पूरे अहीरवाल का नाम रोशन किया।",
    "content": "कनीना/अटेली (महेंद्रगढ़): दक्षिण हरियाणा की माटी में पली-बढ़ी खेल प्रतिभाओं ने एक बार फिर राष्ट्रीय स्तर पर अपना लोहा मनवाया है। पुणे में संपन्न हुई राष्ट्रीय जूनियर फ्रीस्टाइल कुश्ती प्रतियोगिता में अटेली ब्लॉक के गांव सिलारपुर और कनीना के भोजावास अखाड़े के 6 युवा पहलवानों ने 3 स्वर्ण और 2 रजत पदक अपने नाम किए हैं।\n\nइन सभी पहलवानों का चयन आगामी एशियन जूनियर चैंपियनशिप के लिए भारतीय कुश्ती दल में कर लिया गया है। पदक विजेता खिलाड़ियों के गांव पहुंचने पर ढोल-नगाड़ों और आतिशबाजी के साथ भव्य स्वागत जुलूस निकाला गया।\n\nबुजुर्गों ने अखाड़े के गुरुओं को पगड़ी पहनाकर सम्मानित किया। ग्रामीणों ने सरकार से मांग की है कि महेंद्रगढ़ जिले में खेल सुविधाओं के विस्तार के लिए नारनौल और कनीना में आधुनिक मैट वाले इनडोर स्टेडियम व फिजियोथेरेपी केंद्र शीघ्र स्थापित किए जाएं।",
    "category": "महेंद्रगढ़ / नारनौल",
    "categorySlug": "mahendergarh",
    "imageUrl": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
    "imageCaption": "राष्ट्रीय कुश्ती में पदक जीतने के बाद अटेली में ग्रामीणों संग तिरंगा लहराते युवा पहलवान",
    "isBreaking": false,
    "isLeadStory": false,
    "views": 4510,
    "author": "विकास यादव, खेल डेस्क",
    "reporterName": "विकास यादव",
    "district": "Mahendergarh",
    "city": "Kanina",
    "state": "Haryana",
    "status": "PUBLISHED",
    "createdAt": "2026-09-23T13:40:00.000Z",
    "publishedAt": "2026-09-23T13:40:00.000Z",
    "tags": [
      "अटेली",
      "कनीना",
      "महेंद्रगढ़",
      "कुश्ती",
      "खेल",
      "साउथ हरियाणा"
    ]
  }
];

export const sampleSocialPosts: SocialPost[] = [
  {
    id: "sp-001",
    platform: "facebook",
    articleId: "rewari-dharuhera-gurugram-expressway",
    content: "🚩 रेवाड़ी-धारूहेड़ा-गुरुग्राम 4-लेन बाईपास प्रोजेक्ट को 1450 करोड़ की मंजूरी! सुरक्षा व ट्रैफिक प्रबंधन के लिए विशेष प्रबंध। पूरी खबर पढ़ें: https://groundzero.media/article/rewari-dharuhera-gurugram-expressway #SouthHaryana #Rewari #Ahirwal",
    status: "published",
    publishedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    likes: 342,
    shares: 88,
    comments: 24,
  },
  {
    id: "sp-002",
    platform: "twitter",
    articleId: "rewari-dharuhera-gurugram-expressway",
    content: "साउथ हरियाणा किसान सम्मेलन का नारनौल में कल से भव्य आगाज। सरसों व बाजरा उत्पादक किसानों के लिए विशेष तकनीकी सत्र आयोजित होंगे।\n\nविस्तृत रिपोर्ट: groundzero.media/article/rewari-dharuhera-gurugram-expressway #SouthHaryana",
    status: "published",
    publishedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    likes: 128,
    shares: 45,
  },
  {
    id: "sp-003",
    platform: "instagram",
    articleId: "rewari-dharuhera-gurugram-expressway",
    content: "अहीरवाल को बड़ी सौगात! रेवाड़ी 4-लेन बाईपास व धारूहेड़ा लिंक को केंद्र से मिली स्वीकृति।\n.\n.\n#Rewari #SouthHaryana #Ahirwal #GroundZeroNews",
    status: "scheduled",
    scheduledFor: new Date(Date.now() + 1000 * 60 * 45).toISOString(),
  },
  {
    id: "sp-004",
    platform: "whatsapp",
    articleId: "rewari-dharuhera-gurugram-expressway",
    content: "📢 *ग्राउंड ज़ीरो न्यूज़ बुलेटिन*\n\n*साउथ हरियाणा*: नारनौल, रेवाड़ी और गुरुग्राम में नए औद्योगिक क्लस्टर को मंजूरी। 25 हजार युवाओं को मिलेंगे रोजगार के अवसर।\n\nपूरी खबर के लिए लिंक पर क्लिक करें:\nhttps://groundzero.media/article/rewari-dharuhera-gurugram-expressway",
    status: "published",
    publishedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
];

export const sampleCitizenReports: CitizenReport[] = [
  {
    id: "cit-001",
    citizenName: "अनिल यादव (Anil Yadav)",
    phone: "+91 94161 88822",
    email: "anil.yadav@gmail.com",
    district: "महेंद्रगढ़ / Mahendergarh",
    locationDetails: "नारनौल - महेंद्रगढ़ मुख्य मार्ग, नजदीक सिहमा मोड़",
    category: "नागरिक समस्या / इंफ्रास्ट्रक्चर",
    headline: "सिहमा मोड़ के पास सड़क पर 2 फीट गहरा गड्ढा, आए दिन हो रहे बाइक हादसे",
    description: "पिछले 15 दिनों से पाइपलाइन डालने के बाद ठेकेदार ने सड़क को खुला छोड़ दिया है। रात के समय रोशनी न होने के कारण कई वाहन चालक चोटिल हो चुके हैं। प्रशासन तुरंत संज्ञान ले।",
    mediaUrls: [
      "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
    ],
    status: "assigned_to_reporter",
    aiClassification: {
      category: "सड़क सुरक्षा / जनसमस्या",
      urgencyScore: 82,
      summary: "खतरनाक खुला गड्ढा सिहमा मोड़ नारनौल पर दुर्घटना का कारण बन रहा है।",
    },
    assignedReporterId: "usr-reporter-narnaul",
    createdAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  },
  {
    id: "cit-002",
    citizenName: "सुरेंद्र सैनी (Surender Saini)",
    phone: "+91 98120 77711",
    district: "रेवाड़ी / Rewari",
    locationDetails: "बावल इंडस्ट्रियल एरिया सेक्टर 3",
    category: "पर्यावरण / जलभराव",
    headline: "फैक्ट्री का केमिकल युक्त पानी सड़कों पर बह रहा, ग्रामीणों में रोष",
    description: "बावल सेक्टर 3 के पास नाले ओवरफ्लो होने से दूषित पानी खेतों में घुस रहा है जिससे फसलें खराब हो रही हैं।",
    status: "pending_triage",
    aiClassification: {
      category: "पर्यावरण एवं स्वास्थ्य",
      urgencyScore: 78,
      summary: "बावल में औद्योगिक अपशिष्ट जलभराव से फसलों को नुकसान की शिकायत।",
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
];

export const defaultLiveStream: LiveStreamData = {
  id: "live-stream-main",
  channelName: "GROUND ZERO LIVE 24x7 (ग्राउंड ज़ीरो न्यूज़)",
  isLive: true,
  streamUrl: "https://www.youtube.com/embed/dewccxNzJbU?autoplay=1&mute=1",
  streamType: "youtube",
  currentProgram: "साउथ हरियाणा प्राइम बुलेटिन (South Haryana Prime)",
  currentHost: "अमित कुमार (वरिष्ठ संपादक)",
  upcomingProgram: "ग्राउंड ज़ीरो स्पेशल डिबेट: अहीरवाल की राजनीति",
  viewerCount: 14280,
  crawlTickerText: "ग्राउंड ज़ीरो एक्सक्लूसिव: हरियाणा में मौसम विभाग का नया अलर्ट | दक्षिण हरियाणा में बाजरा खरीद केंद्रों पर विशेष निगरानी | शिक्षा और स्वास्थ्य सुविधाओं पर सरकार की नई नीति",
};

export const sampleEPaperEditions: EPaperEdition[] = [
  {
    id: "edition-mgarh",
    date: new Date().toISOString().split("T")[0],
    formattedDate: new Date().toLocaleDateString("hi-IN", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    editionName: "महेंद्रगढ़ - नारनौल मुख्य संस्करण",
    editionSlug: "mahendergarh",
    district: "महेंद्रगढ़",
    pages: [
      {
        pageNumber: 1,
        title: "पेज 1: मुख्य पृष्ठ (हरियाणा एवं राष्ट्रीय सुर्खियां)",
        imageUrl: "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 2,
        title: "पेज 2: नारनौल - अटेली - कनीना प्रादेशिक हलचल",
        imageUrl: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 3,
        title: "पेज 3: अहीरवाल विचार, संपादकीय एवं ग्रामीण चौपाल",
        imageUrl: "https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 4,
        title: "पेज 4: खेल, रोजगार, कृषि मंडी भाव एवं युवा जगत",
        imageUrl: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
  {
    id: "edition-rewari",
    date: new Date().toISOString().split("T")[0],
    formattedDate: new Date().toLocaleDateString("hi-IN", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    editionName: "रेवाड़ी - बावल औद्योगिक विशेष संस्करण",
    editionSlug: "rewari",
    district: "रेवाड़ी",
    pages: [
      {
        pageNumber: 1,
        title: "पेज 1: मुख्य पृष्ठ (रेवाड़ी जिला एवं हाईवे अपडेट)",
        imageUrl: "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 2,
        title: "पेज 2: बावल इंडस्ट्रियल कॉरिडोर एवं धारूहेड़ा डायरी",
        imageUrl: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 3,
        title: "पेज 3: विचार एवं प्रशासनिक समीक्षा",
        imageUrl: "https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 4,
        title: "पेज 4: खेल, बाजार भाव एवं क्लासिफाइड",
        imageUrl: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
  {
    id: "edition-dadri-jhajjar",
    date: new Date().toISOString().split("T")[0],
    formattedDate: new Date().toLocaleDateString("hi-IN", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    editionName: "चरखी दादरी - झज्जर - बहादुरगढ़ संस्करण",
    editionSlug: "dadri-jhajjar",
    district: "चरखी दादरी",
    pages: [
      {
        pageNumber: 1,
        title: "पेज 1: मुख्य पृष्ठ (दादरी-झज्जर प्रादेशिक लीड)",
        imageUrl: "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 2,
        title: "पेज 2: बहादुरगढ़ औद्योगिक व ग्रामीण अंचल",
        imageUrl: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 3,
        title: "पेज 3: शिक्षा, रोजगार एवं ग्रामीण चौपाल",
        imageUrl: "https://images.unsplash.com/photo-1586339949916-3e9457bef6d3?auto=format&fit=crop&w=1200&q=80",
      },
      {
        pageNumber: 4,
        title: "पेज 4: दादरी-झज्जर मंडी भाव एवं युवा जगत",
        imageUrl: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
];

export const sampleAds: AdCampaign[] = [
  {
    id: "ad-lead-1",
    advertiserName: "Haryana Agro Industries Corp",
    campaignTitle: "हरियाणा कृषि यंत्र एवं सोलर पंप सब्सिडी अभियान 2026",
    placement: "header_leaderboard",
    imageUrl: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1200&q=80",
    targetUrl: "https://agriharyana.gov.in",
    startDate: "2026-03-01",
    endDate: "2026-04-30",
    impressions: 48920,
    clicks: 1680,
    status: "active",
    districtTarget: "Haryana",
  },
  {
    id: "ad-side-1",
    advertiserName: "राव तुलाराम मेमोरियल सुपर-स्पेशलिटी हॉस्पिटल रेवाड़ी",
    campaignTitle: "24x7 इमरजेंसी एवं एडवांस कार्डियक केयर सेंटर",
    placement: "sidebar_sticky",
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=600&q=80",
    targetUrl: "https://example.com/hospital",
    startDate: "2026-02-15",
    endDate: "2026-05-15",
    impressions: 34150,
    clicks: 1120,
    status: "active",
    districtTarget: "Rewari",
  },
  {
    id: "ad-article-1",
    advertiserName: "आदर्श डिफेंस एकेडमी नारनौल",
    campaignTitle: "NDA, CDS, Airforce एवं हरियाणा पुलिस स्पेशल फिजिकल बैच शुरू",
    placement: "in_article",
    imageUrl: "https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=800&q=80",
    targetUrl: "https://example.com/defence-academy",
    startDate: "2026-03-01",
    endDate: "2026-06-01",
    impressions: 29400,
    clicks: 980,
    status: "active",
    districtTarget: "Mahendergarh",
  },
  {
    id: "ad-foot-1",
    advertiserName: "साउथ हरियाणा एमएसएमई & ऑटो एक्सपो",
    campaignTitle: "मानेसर-बावल औद्योगिक प्रदर्शनी 2026 - निःशुल्क पंजीकरण",
    placement: "footer_banner",
    imageUrl: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=1200&q=80",
    targetUrl: "https://example.com/msme-expo",
    startDate: "2026-03-10",
    endDate: "2026-04-10",
    impressions: 16200,
    clicks: 530,
    status: "active",
    districtTarget: "Gurugram / Rewari",
  },
];

export const sampleVideos: VideoItem[] = [
  {
    id: "vid-1",
    title: "नारनौल मेडिकल कॉलेज ट्रॉमा सेंटर का ग्राउंड रियलिटी टेस्ट: क्या मरीजों को मिल रही 24x7 सुविधा?",
    description: "ग्राउंड ज़ीरो की खोजी रिपोर्ट - दक्षिण हरियाणा के सबसे बड़े चिकित्सा संस्थान में आईसीयू, डायलिसिस और आपातकालीन सेवाओं की वास्तविक स्थिति।",
    youtubeId: "dewccxNzJbU",
    thumbnailUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80",
    duration: "08:45",
    category: "स्वास्थ्य",
    location: "Narnaul",
    format: "16:9",
    isShort: false,
    views: 42150,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "vid-2",
    title: "अटेली और कनीना अनाज मंडी में बाजरा खरीद का सीधा हाल: किसानों से तीखे सवाल-जवाब",
    description: "मंडी में नमी मापक यंत्र और बारदाने की कमी को लेकर किसानों ने अपनी समस्याएं खुलकर रखीं। देखिए ग्राउंड रिपोर्ट।",
    youtubeId: "ScMzIvxBSi4",
    thumbnailUrl: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80",
    duration: "06:20",
    category: "कृषि",
    location: "Ateli",
    format: "16:9",
    isShort: false,
    views: 29800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: "vid-3",
    title: "रेवाड़ी-दिल्ली हाईवे पर भारी जाम: 60 सेकंड में जानिए वैकल्पिक रूट!",
    description: "धारूहेड़ा फ्लाईओवर के पास मरम्मत कार्य से लंबा ट्रैफिक जाम। पुलिस ने जारी किया रूट डायवर्जन प्लान।",
    youtubeId: "ScMzIvxBSi4",
    thumbnailUrl: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=600&q=80",
    duration: "00:58",
    category: "ट्रैफिक",
    location: "Rewari",
    format: "9:16",
    isShort: true,
    views: 89400,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "vid-4",
    title: "झज्जर के पहलवान दीपक का नेशनल चैंपियनशिप में स्वर्ण पदक! सुनिए क्या बोले चैंपियन",
    description: "दक्षिण हरियाणा के अखाड़ों की शान झज्जर के बेटे ने फिर रोशन किया नाम। नेशनल जूनियर कुश्ती में गोल्ड मेडल जीता।",
    youtubeId: "dewccxNzJbU",
    thumbnailUrl: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=600&q=80",
    duration: "00:48",
    category: "खेल",
    location: "Jhajjar",
    format: "9:16",
    isShort: true,
    views: 65120,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "vid-5",
    title: "महेंद्रगढ़ किले का 4K ड्रोन व्यू: अहीरवाल की आन-बान-शान",
    description: "इतिहास के पन्नों से जीवंत होता महेंद्रगढ़ का ऐतिहासिक किला। देखिए विहंगम हवाई दृश्य।",
    youtubeId: "dewccxNzJbU",
    thumbnailUrl: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80",
    duration: "00:54",
    category: "संस्कृति",
    location: "Mahendergarh",
    format: "9:16",
    isShort: true,
    views: 114500,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: "vid-6",
    title: "गुरुग्राम-रेवाड़ी आरआरटीएस (RRTS) रैपिड रेल प्रोजेक्ट: जमीन अधिग्रहण और स्टेशनों की पूरी सूची",
    description: "दिल्ली से अलवर तक जाने वाली रैपिड ट्रेन परियोजना में धारूहेड़ा, रेवाड़ी और बावल स्टेशन का मास्टर प्लान।",
    youtubeId: "ScMzIvxBSi4",
    thumbnailUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=800&q=80",
    duration: "11:15",
    category: "विकास",
    location: "Rewari",
    format: "16:9",
    isShort: false,
    views: 53200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
];

export const samplePhotoAlbums: PhotoAlbum[] = [
  {
    id: "album-1",
    title: "जल महल और ऐतिहासिक बीरबल का छत्ता: नारनौल की स्थापत्य कला",
    slug: "narnaul-heritage-monuments",
    description: "मुगल और राजपूत वास्तुकला का अनुपम संगम, नारनौल के ऐतिहासिक स्मारकों की एक्सक्लूसिव फोटो गैलरी।",
    photographerName: "सुनील यादव (ग्राउंड ज़ीरो फोटो जर्नलिस्ट)",
    location: "नारनौल, महेंद्रगढ़",
    coverImageUrl: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    photos: [
      {
        id: "p-1",
        url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80",
        caption: "जल महल का मनोरम दृश्य, जल के बीच खड़ा ऐतिहासिक स्थापत्य",
      },
      {
        id: "p-2",
        url: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
        caption: "बीरबल के छत्ते की प्राचीन मेहराबें और नक्काशीदार खंभे",
      },
      {
        id: "p-3",
        url: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
        caption: "ऐतिहासिक बावड़ी की सीढ़ियां और पुरातात्विक संरचना",
      },
      {
        id: "p-4",
        url: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80",
        caption: "सूर्यास्त के समय नारनौल किले का मनमोहक क्षितिज",
      },
    ],
  },
  {
    id: "album-2",
    title: "दक्षिण हरियाणा का पारंपरिक पशु मेला: कनीना से लोक संस्कृति की रंगीन छटा",
    slug: "kanina-traditional-cattle-fair",
    description: "अहीरवाल की ग्रामीण संस्कृति, मुर्राह नस्ल की भैंसें और पारंपरिक परिधानों में सजे किसान।",
    photographerName: "अमित कुमार (वरिष्ठ संपादक)",
    location: "कनीना, महेंद्रगढ़",
    coverImageUrl: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1200&q=80",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    photos: [
      {
        id: "p-21",
        url: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1200&q=80",
        caption: "कनीना पशु मेले में चैंपियन मुर्राह भैंसों की प्रतियोगिता",
      },
      {
        id: "p-22",
        url: "https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=1200&q=80",
        caption: "पारंपरिक हुक्का चौपाल और ग्रामीण बुजुर्गों की पंचायत",
      },
      {
        id: "p-23",
        url: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1200&q=80",
        caption: "मेले में सजी कृषि उपकरणों और हस्तशिल्प की दुकानें",
      },
    ],
  },
  {
    id: "album-3",
    title: "रेवाड़ी का हेरिटेज स्टीम लोकोमोटिव शेड: भारतीय रेल का जीवित इतिहास",
    slug: "rewari-steam-loco-heritage-shed",
    description: "1893 में स्थापित एशिया का एकमात्र कामकाजी स्टीम लोको शेड, जहाँ आज भी छुक-छुक करती हैं ऐतिहासिक भाप गाड़ियां।",
    photographerName: "राजेश वर्मा (चीफ एडमिन)",
    location: "रेवाड़ी जंक्शन",
    coverImageUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1200&q=80",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    photos: [
      {
        id: "p-31",
        url: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1200&q=80",
        caption: "अकबर स्टीम इंजन WP 7161 अपने पूर्ण वैभव में",
      },
      {
        id: "p-32",
        url: "https://images.unsplash.com/photo-1513407030348-c983a97b98d8?auto=format&fit=crop&w=1200&q=80",
        caption: "विंटेज कंट्रोल पैनल और पीतल के ऐतिहासिक गेज मीटर",
      },
      {
        id: "p-33",
        url: "https://images.unsplash.com/photo-1509749837427-ac94a2553d0e?auto=format&fit=crop&w=1200&q=80",
        caption: "शेड में भाप का दबाव बनाते हुए अनुभवी लोको पायलट",
      },
    ],
  },
];

export const initialPushAlerts: PushAlert[] = [
  {
    id: "alert-1",
    title: "मौसम अलर्ट: दक्षिण हरियाणा में तेज आंधी और बारिश की चेतावनी",
    message: "मौसम विभाग ने महेंद्रगढ़, रेवाड़ी और झज्जर में अगले 3 घंटों के लिए येलो अलर्ट जारी किया है।",
    targetUrl: "/article/art-1",
    category: "मौसम",
    district: "महेंद्रगढ़",
    isBreaking: true,
    sentAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    sentBy: "अमित कुमार (प्रधान संपादक)",
    deliveredCount: 45200,
  },
  {
    id: "alert-2",
    title: "बड़ी खबर: धारूहेड़ा-रेवाड़ी NH48 पर भीषण जाम खुला",
    message: "फ्लाईओवर मरम्मत कार्य पूरा होने के बाद दोनों तरफ का यातायात सामान्य रूप से शुरू हुआ।",
    targetUrl: "/videos",
    category: "ट्रैफिक",
    district: "रेवाड़ी",
    isBreaking: false,
    sentAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    sentBy: "डिजिटल न्यूज़ डेस्क",
    deliveredCount: 38100,
  },
  {
    id: "alert-3",
    title: "नारनौल मेडिकल कॉलेज: नई 24x7 डायलिसिस विंग का उद्घाटन",
    message: "स्वास्थ्य मंत्री ने किया अत्याधुनिक डायलिसिस यूनिट का शुभारंभ। मरीजों को मिलेगी मुफ्त सुविधा।",
    targetUrl: "/location/mahendergarh",
    category: "स्वास्थ्य",
    district: "महेंद्रगढ़",
    isBreaking: false,
    sentAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    sentBy: "नवीन शर्मा (संवाददाता)",
    deliveredCount: 29400,
  },
];

export const sampleAssignments: EditorialAssignment[] = [
  {
    id: "asg-001",
    title: "कनीना और अटेली अनाज मंडी में सरसों-बाजरा खरीद व्यवस्था का ग्राउंड रियलिटी चेक",
    description: "कनीना व अटेली मंडी में किसानों से बातचीत करें। नमी जांच, बारदाना उपलब्धता और व्यापारियों द्वारा की जा रही खरीद का प्रत्यक्ष जायजा लेकर फोटो और रिपोर्ट भेजें।",
    reporterId: "usr-reporter-narnaul",
    reporterName: "नवीन शर्मा (Narnaul / Mahendergarh)",
    editorId: "usr-district-editor",
    editorName: "सतीश यादव (South Haryana Bureau Chief)",
    status: "in_progress",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    location: "Kanina / Mahendergarh",
    category: "कृषि / किसान",
    priority: "high",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "asg-002",
    title: "रेवाड़ी-धारूहेड़ा-मानेसर एक्सप्रेसवे कॉरिडोर निर्माण कार्य की प्रगति रिपोर्ट",
    description: "एनएचएआई और लोक निर्माण अधिकारियों से मिलकर नई एलिवेटेड सड़कों और फ्लाईओवर्स के निर्माण की स्थिति पर ग्राउंड इनपुट लें।",
    reporterId: "usr-reporter-narnaul",
    reporterName: "राजेश यादव (Rewari Bureau)",
    editorId: "usr-editor-in-chief",
    editorName: "अमित कुमार (Editor-in-Chief)",
    status: "assigned",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    location: "Rewari / Gurugram",
    category: "साउथ हरियाणा",
    priority: "urgent",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "asg-003",
    title: "नूह (मेवात) कोटला पेयजल पाइपलाइन और नहरी जल वितरण की जमीनी पड़ताल",
    description: "तावडू और पुन्हाना के गांवों में जाकर देखें कि क्या टेल तक शुद्ध पेयजल पहुंच पा रहा है। ग्रामीणों की बाइट्स रिकॉर्ड करें।",
    reporterId: "usr-reporter-narnaul",
    reporterName: "आरिफ खान (Nuh Bureau)",
    editorId: "usr-district-editor",
    editorName: "सतीश यादव (South Haryana Bureau Chief)",
    status: "in_progress",
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    location: "Nuh / Mewat",
    category: "जनसरोकार",
    priority: "high",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
];


